### ISSUE TITLE
Custom class functions don't have reference to self / @

### ISSUE THREAD

**Issue by kvn-prhn** [devwerewolf/werewolf-dot-dev#3]
I have this class with a custom function `my_func` 

```moon
class ExampleCustomFunc
  new: =>
    print @ -- not nil
  my_func: =>
    print @ -- nil

print 'ExampleCustomFunc'
a = spawn ExampleCustomFunc
a.my_func()
```
`new` is called first from the `spawn` call, and `my_func()` is manually called later.

This is the output in console
```
ExampleCustomFunc 
table: 0x112 
nil
```

In the custom function, `@` (for self) was `nil`

**Comment by devwerewolf** [comment]
In MoonScript, you call class functions with `\` rather than `.` or `:`.

```moon
class ExampleCustomFunc
  new: =>
    print @
  my_func: =>
    print @

print 'ExampleCustomFunc'
a = spawn ExampleCustomFunc
a\my_func() -- here
```

You can learn more about object oriented MoonScript here (the official online manual): https://moonscript.org/reference/#the-language/object-oriented-programming

This can be confusing if you're used to a language which only uses `.`, or if you're used to Lua's `:` syntax. Just a facet of the language to get used to 🙂
